### ISSUE TITLE
Disqus?

### ISSUE THREAD

**Issue by EmmanuelBeziat** [reverland/blog-next#3]
I saw you just added Disqus to your posts.

As you put a "disqus" boolean in your markdown metadatas, you could put a condition on your Post.vue: 

``` vue
<div class="ui segment" v-if="disqus">
  <disqus :shortname="shortname"></disqus>
</div>
```

(Of course, assuming the "disqus" variable is set as your markdown metadata).

~~By the way, is it normal that your shortname is still "shortname"? It seem to work on the site, but you won't be able to manage your comments if you don't link it to an existing account shortname.~~

**Comment by EmmanuelBeziat** [comment]
About the shortname: I got it when I saw your config file for webpack. Really clever!

**Comment by reverland** [comment]
@EmmanuelBeziat how's the feeling about nuxt.js?

**Comment by EmmanuelBeziat** [comment]
So far, I didn't check enough yet. I've had some issues with the current vue2 version of my site, and I focused on it (unfortunately, with no success for now).

From what I could saw: 
* I like the "automatic-routes" approach: when a .vue file is created in "view" folder, a route with the name is instantly created.
* I couldn't find a lot of way to customize it. I have the feeling that it's using more of its own content and workflow than the classis webpack + vue (+ plugins), and I don't know if I could be able to use it to generate some custom files (like the feed or anything).

So I didn't learned much. It would be helpful to find a concrete project that could be used with it.

**Comment by reverland** [comment]
automatic route？sounds interesting

**Comment by EmmanuelBeziat** [comment]
Yup :) https://nuxtjs.org/guide/routing

**Comment by reverland** [comment]
@EmmanuelBeziat I've checked how nuxt.js implement its route, nested dynamic routes makes it really complex...
