### ISSUE TITLE
How to integrate with disqus?

### ISSUE THREAD

**Issue by hailiang-wang** [reverland/blog-next#4]
@reverland Nice job.

I want to setup a blog with blog-next, but could you tell me how to integrate with disqus?
I saw someone mentioned it in https://github.com/reverland/blog-next/issues/3, but from your site, I don't get the comment area in your articles.

**Comment by hailiang-wang** [comment]
What I have done on my laptop?

# install
npm install

# register disqus
![image](https://cloud.githubusercontent.com/assets/3538629/23413300/36833382-fe13-11e6-80bb-6d7c62211caa.png)

# update config

![image](https://cloud.githubusercontent.com/assets/3538629/23413300/36833382-fe13-11e6-80bb-6d7c62211caa.png)

# Rebuild and serve
![image](https://cloud.githubusercontent.com/assets/3538629/23413519/df68f310-fe13-11e6-82ff-38ae8bcf2bc6.png)

No disqus?

**Comment by EmmanuelBeziat** [comment]
@Samurais Allow me to answer here; you have to use a vue component: https://www.npmjs.com/package/vue-disqus

**Comment by hailiang-wang** [comment]
@EmmanuelBeziat Yes, it is installed. 

How to configure this feature. 
My site's url is https://samurais.github.io
And in disqus, it is configured as well.
![image](https://cloud.githubusercontent.com/assets/3538629/23457293/481c0070-feb2-11e6-8429-9b3e1e6f6e41.png)


But the comment area does not render. 
![image](https://cloud.githubusercontent.com/assets/3538629/23457351/86814640-feb2-11e6-9a03-c05082eb05f5.png)

Here is the static files - https://github.com/Samurais/samurais.github.io/tree/master
The project codes - https://github.com/Samurais/samurais.github.io/tree/develop
**blog-config.js**
```
module.exports = {
  scheme: 'https',
  host: 'samurais.github.io',
  title: '52chatbot',
  subTitle: 'Noble is not born, but trained.',
  disqus: 'trained'
}
```

**Comment by hailiang-wang** [comment]
Thanks @reverland , problem is fixed.

Install 
```
 "vue-disqus": "^1.0.2",
```
