### ISSUE TITLE
[iPhone] 日期标签被识别为数字，唤起呼叫

### ISSUE THREAD

**Issue by hailiang-wang** [reverland/blog-next#7]
在手机上打开链接 - http://blog.chatbot.io/archives
点击 "日期标签"

![image](https://cloud.githubusercontent.com/assets/3538629/24826786/733ed008-1c70-11e7-8df2-281a5b9acf13.png)

系统唤起了呼叫电话号码的对话窗。

![image](https://cloud.githubusercontent.com/assets/3538629/24826776/4dd57c5e-1c70-11e7-9a46-2ef1ef64af9f.png)

**Comment by hailiang-wang** [comment]
@reverland Get a bug with iPhone. Please help.

**Comment by reverland** [comment]
gg……明天看看
